In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [2]:
mpl.rc('lines', linewidth=1, color='black')
mpl.rcParams['font.family'] = 'serif'
mpl.rcParams['font.serif'] = ['Times New Roman'] + mpl.rcParams['font.serif']
font = {'weight': 'normal', 'size': 15}
mpl.rc('font', **font)  # pass in the font dict as kwargs
lw = 2
fs = 12

In [3]:
import MDAnalysis as mda
from MDAnalysis import transformations as trans

/data/home/jxzhu/.conda/envs/gnn/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
u = mda.Universe("coord.xyz")
transform = trans.boxdimensions.set_dimensions([10, 10, 20, 90, 90, 90])
u.trajectory.add_transformations(transform)

In [10]:
ag0 = u.select_atoms("relprop z > 5 (name O)")

In [11]:
ag1 = u.select_atoms("relprop z > 5 (name O)", updating=True)

In [19]:
for ii in range(len(u.trajectory)):
    u.trajectory[ii]
    print(ag0.positions)
    print(ag1.positions)

[[ 1.  1. 10.]]
[[ 1.  1. 10.]]
[[1. 1. 2.]]
[]
