In [ ]:
import numpy as np
import MDAnalysis as mda
from MDAnalysis import transformations as trans

In [ ]:
from WatAnalysis.hbonds.m_mda import PartialHBAnalysis

In [ ]:
# load trajectory
u = mda.Universe("../input_data/interface.psf", "../input_data/trajectory.xyz")
dim = [16.869, 16.869, 41.478, 90, 90, 120]
transform = trans.boxdimensions.set_dimensions(dim)
u.trajectory.add_transformations(transform)

In [ ]:
hbonds = PartialHBAnalysis(universe=u, region=[2.7, 4.5], surf_ids=[np.arange(871, 906),
                                     np.arange(691, 726)],donors_sel="name O",
                           hydrogens_sel="name H",
                           acceptors_sel="name O")
hbonds.run()
print(hbonds.results.hbonds.shape)

In [18]:
import numpy as np

a = np.arange(5, 15)
b = -np.arange(1, 21, 2)
print(a, b)
c = np.concatenate(([a], [b]), axis=0)
print(c)
min_ids = np.argmin(np.abs(c), axis=0)
print(min_ids)
print(np.transpose(c)[min_ids])

[ 5  6  7  8  9 10 11 12 13 14] [ -1  -3  -5  -7  -9 -11 -13 -15 -17 -19]
[[  5   6   7   8   9  10  11  12  13  14]
 [ -1  -3  -5  -7  -9 -11 -13 -15 -17 -19]]
[1 1 1 1 0 0 0 0 0 0]
[[ 6 -3]
 [ 6 -3]
 [ 6 -3]
 [ 6 -3]
 [ 5 -1]
 [ 5 -1]
 [ 5 -1]
 [ 5 -1]
 [ 5 -1]
 [ 5 -1]]
